name: flutter_tex

description: A Flutter package to render Maths, Physics, Chemistry, Statistics equations and expressions based on LaTeX, TeX, and MathML with HTML and JavaScript support.

version: 5.1.8

homepage: https://github.com/Shahxad-Akram/flutter_tex
publish_to: none


environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter_plus: 
    path: ../webview_flutter_plus
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1
  markdown: ^7.3.0
  web: ^1.1.1
  webview_flutter_wkwebview: ^3.22.0
  webview_flutter_android: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - packages/flutter_tex/core/mathjax_core.js
    - packages/flutter_tex/core/flutter_tex.js
    - packages/flutter_tex/core/flutter_tex.css
    - packages/flutter_tex/core/flutter_tex.html